### ISSUE TITLE
filebeat7.1 设置 template 名无效

### ISSUE THREAD

**Issue by mattshma** [mattshma/bigdata#155]
在 filebeat 7.1 中，filebeat.yml 有如下配置：
```
setup.template.enabled: true
setup.template.name: "myTemplate"
setup.template.pattern: "myTemplate-*"
setup.template.fields: "${path.config}/fields.yml"
setup.template.overwrite: true
setup.template.settings:
  index.number_of_shards: 5

output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["http://es:9200"]
  index: "myTemplate-%{+yyyy.MM.dd}"
```
重启 filebeat 后，发现送往 es 的文件名一直是 filebeat-yyyyMMdd-0001 这种类型的，后来查了下，es 7.0 后，使用了 index lifecycle management，可见 [issues-11866](https://github.com/elastic/beats/issues/11866)，这里有两种解决方法：
- 设置 `setup.ilm.enabled: false`
- 或设置 `setup.ilm.rollover_alias: "myTemplate"`
